### ISSUE TITLE
Can the heightmap effect move by dragging around like the default landmass brush

### ISSUE THREAD

**Issue by delebash** [AWeinb/SimplerLandmassBlueprints#1]
I have tried setting up a spline and then thought to add a heightmap effect, but I cannot get it to work.

I am trying to see if I can make it do a non-destructive landscape stamp like  

https://www.unrealengine.com/marketplace/en-US/product/landscape-stamping-tool-100-custom-brushes

Awesome job, this is a very cool feature.  Cheers!

**Comment by AWeinb** [comment]
Should be possible. I need to check it. 
With the change in the ticket #2 it should work out of the box but be careful as the redraw is triggered often.
Thanks, glad you like it :)

**Comment by delebash** [comment]
Awesome!
