### ISSUE TITLE
Set the effect location to the same as the brush location.

### ISSUE THREAD

**Issue by delebash** [AWeinb/SimplerLandmassBlueprints#2]
Example:  When using a heightmap effect you can change the location of the effect using x and y origin.  However, the x and y origin are not the same as the unreal location of the brush.

First picture shows the brush location.
Second picture shows the effect x and y location.  I would be cool if where ever I clicked on the landscape with my brush then that would be the effect location.

![UnrealEditor_fF66wKQiqp](https://user-images.githubusercontent.com/2220160/188294855-c02b2fa1-7018-44de-8cdb-4a258c963e39.png)

![UnrealEditor_ByZ3r77Ug2](https://user-images.githubusercontent.com/2220160/188294860-3305d8f5-559e-4a42-81de-69d2345b8197.png)

TY.

**Comment by AWeinb** [comment]
![grafik](https://user-images.githubusercontent.com/4525893/193465628-ba6bd47f-9ec2-4c9b-a6dd-c05e2c1fe6e2.png)

**Comment by AWeinb** [comment]
This seems to do the trick if you add it to the HeightMapEffect.

**Comment by delebash** [comment]
Awesome, thank you very much.  Cheers!!!

**Comment by delebash** [comment]
I have already added this feature to my free landscape plugin.  I will now integrate yours since it is also opensource and fits well with mine.  Check it out.  https://github.com/delebash/UnrealMapboxBridgePlugin

**Comment by AWeinb** [comment]
> Awesome, thank you very much. Cheers!!!

Glad i could help! :)
