### ISSUE TITLE
Remove hard coded path for LandmassEffectBrush

### ISSUE THREAD

**Issue by delebash** [AWeinb/SimplerLandmassBlueprints#4]
The folder structure is Editor>Landscape>LandmassEffectBrush

If I move LandmassEffectBrush folder to the root of my Content folder the brush stops working.  Folder structure I want to have is Content>LandmassEffectBrush

Your plugin is awesome!!!

**Comment by AWeinb** [comment]
Thats a problem which i also encountered when improving the folder structure. It seems that one has to very careful with moving files.
Did you move the files in UE? Did you try to recompile the classes (Perhaps only the ones that are relevant for you)?
If i remember correctly there could be a migration feature in UE. This could be used to migrate files from one project to another.

**Comment by delebash** [comment]
ok thanks.
