### ISSUE TITLE
Having trouble getting the class defaults of your blueprint.

### ISSUE THREAD

**Issue by delebash** [AWeinb/SimplerLandmassBlueprints#5]
I am trying to automate your plugin and need access the the heightmap property.  For some reason I can't get to it using code like I normally do.  Please see this post for details https://forums.unrealengine.com/t/how-do-you-get-nested-editor-properties-from-class-default-object-using-python/683451.  Any help would be appreciated. TY!

**Comment by AWeinb** [comment]
Did you try to debug or print out all elements in blueprint_class_default? Maybe this could yield a clue on the correct key.

**Comment by delebash** [comment]
Yeah I did and it is not showing up.  I will keep working on it.
